### ISSUE TITLE
Timing in CAAnimation is incomplete

### ISSUE THREAD

**Issue by lsinger** [cappuccino/cappuccino#1097]
As of now, only linear timing is support -- as far as I can see (see https://github.com/280north/cappuccino/tree/master/AppKit/CoreAnimation). See http://iphonedevelopment.blogspot.com/2010/12/more-animation-curves-than-you-can.html for public domain implementations of some timing functions. These could be used in Cappuccino.

**Comment by daboe01** [comment]
@cacaodev can we close this one now?
