### ISSUE TITLE
CPTableView always sends tableViewSelectionDidChange

### ISSUE THREAD

**Issue by kuon** [cappuccino/cappuccino#1375]
In the documentation of the delegate methods of `CPTableView`, it is stated that `tableViewSelectionDidChange:` is triggered only by user action (clicking the table). But in reality, `tableViewSelectionDidChange:` is sent to the delegate for all selection change like `selectRowIndexes:byExtendingSelection:`.

We should either update the documentation, or, more appropriately, change the behaviour for the delegate to be notified only when the selection is modified by user action.

**Comment by daboe01** [comment]
i am not sure we should change this issue more than 10 years later.
a lot of cappuccino code in the meantime is relying on this behavior.
i suggest we update the documentation instead of fixing.
any objections?

**Comment by enquora** [comment]
I don't have time to look at this immediately, but can correct (canonical) behaviour be restored using just a category? Something we could include in source or on a wiki page to be applied optionally.

We don't have nearly the number of users which were current with the original filing of the issue.
Perhaps we could canvas on Gitter?

My preference is to follow canonical behaviour, but neither can we afford to break a non-trivial number of in-production apps. Having said that, most extant apps which might be affected and are troublesome to update are likely running happily on Narwhal. Updating to Node likely involves fixing a few other breaking changes, like CPBox borders.

**Comment by daboe01** [comment]
looking at apple's documentation, the behaviour with respect to delegate notfications is not defined at all.
having a look at our source code, changing this would be quite risk with respect to introducing bugs.
furthermore, we have a lot of borderline methods such as selectAll: and friends that can be both called by the user (menu shortcut) or programmatically.
my suggtestion is to just close this issue (no need to document here when undocumented by apple).

**Comment by enquora** [comment]
> looking at apple's documentation, the behaviour with respect to delegate notfications is not defined at all. having a look at our source code, changing this would be quite risk with respect to introducing bugs. furthermore, we have a lot of borderline methods such as selectAll: and friends that can be both called by the user (menu shortcut) or programmatically. my suggtestion is to just close this issue (no need to document here when undocumented by apple).

I concur. A new issue can be created if further information changes this assessment.
