### ISSUE TITLE
Deprecated sourceURL declaration

### ISSUE THREAD

**Issue by timeimp** [cappuccino/cappuccino#1950]
When running index-debug.html, the Webkit Inspector in Chrome 29.0.1541.0 dev spits out numerous errors like this one: 

`//@ sourceURL=" source URL declaration is deprecated, "//# sourceURL=" declaration should be used instead.`

After searching around online, it appears that all the major browsers are moving to the new sourceURL format 'soon': 
http://updates.html5rocks.com/2013/06/sourceMappingURL-and-sourceURL-syntax-changed

Will the compiler be needed be updated at some point once all the browsers have moved to this in their stable release channels?

**Comment by daboe01** [comment]
@mrcarlberg can we close this one now?

**Comment by mrcarlberg** [comment]
Good catch! We can close this as all browsers do support the new syntax and the Cappuccino framework is also using it.

**Comment by daboe01** [comment]
+#wont-fix
