### ISSUE TITLE
0.9.7_alpha1 documentation incomplete

### ISSUE THREAD

**Issue by GlennAustin** [cappuccino/cappuccino#1956]
Classes such as CPArray are no longer shown in the generated documentation.

Upon investigation, all files with leading underscores are ignored.
All symbols with leading underscores are ignored.

The current CPArray is located in _CPArray.j (leading underscore), and the implementation is based upon a class with a leading underscore.

**Comment by daboe01** [comment]
@ahankinson is this still an issue?

**Comment by ahankinson** [comment]
The API documentation online has not been updated to 0.9.8, so yes, it is still an issue.

**Comment by Dogild** [comment]
It will normally be updated with release ;)
