### ISSUE TITLE
Where is XcodeCapp?

### ISSUE THREAD

**Issue by swisspol** [cappuccino/cappuccino#2084]
There's no XcodeCapp app installed anywhere in the installation directory contrary to what the tutorial says:
http://www.cappuccino-project.org/learn/xcode-basics.html

_Clean install of Cappuccino 0.9.7 using bootstrap.sh on OS X 10.9.2._

**Comment by alanfalima** [comment]
I'm getting a lot of warnings while trying to install Cappuccino using the bootstrap.sh, things like:

include/narwhal.h:148:9: warning: data argument not used by format string [-Wformat-extra-args]
        THROW("NULL toString!");

narwhal.c:69:19: warning: expression result unused [-Wunused-value]
FUNCTION(NW_read, ARG_UTF8(path))

in the end of the script, it says its all fine, but many things are not compiled, like the XcodeCapp, is there anything different that should be done?

**Comment by Dogild** [comment]
HI @alanfalima 

Just ignore the warnings generated by narwhal... ;)

For XcodeCapp, what cappuccino said exactly ? Is it the first time you have installed cappuccino ? Are you on a mac ?

**Comment by alanfalima** [comment]
It's the first time I'm trying to install, when I just ignore the warnings, the script finish without errors but I can't find the XcodeCapp.app in the installation directory (default btw), also there isn't even the directory "support" in the "/usr/local/narwhal/packages/cappuccino" as the tutorial says

**Comment by Dogild** [comment]
The tutorial are a bit outdated :/ we will work on that the next weeks thought !

For XcodeCapp, glad it works from the source, but when you have installled cappuccino you should find it in the Application folder. What is going on when you use Spotlight ?

**Comment by alanfalima** [comment]
Now that I have built it from the source with Xcode, its on the Application folder, but before it there was nothing there and nothing on Spotlight
