### ISSUE TITLE
Objective-j can compile merge conflict code

### ISSUE THREAD

**Issue by Dogild** [cappuccino/cappuccino#2220]
This code can be compiled :

``` obj
<<<<<<< HEAD:CPView.j
    var origin = _frame.origin;
=======
    var origin = _frame.origin;
>>>>>>> origin:CPView.j
```

**Comment by daboe01** [comment]
@mrcarlberg is this still an issue?

**Comment by mrcarlberg** [comment]
Yes, we can close this one as we don't use gcc or clang as a preprocessor anymore. The preprocessor is built into our compiler.
