### ISSUE TITLE
nib2cib broken by commit 42e12fae24d88bcb6784f439a74c1f43bc2b5a51

### ISSUE THREAD

**Issue by enquora** [cappuccino/cappuccino#2497]
Commit applying pull request [nib2cib: discard warnings in the nib file](https://github.com/cappuccino/cappuccino/pull/2485), causes nib2cib to fail with error message  on my installation 
`[_CPJavaScriptArray filteredArrayUsingBlock:] unrecognized selector sent to instance ...`

**Comment by cacaodev** [comment]
Thanks. I reverted the commit.
