### ISSUE TITLE
Missing methods called

### ISSUE THREAD

**Issue by bedalton** [cappuccino/cappuccino#2586]
I'm not an experienced programmer, and I don't really know much about GitHub, but I'm working on a plugin for Intellij, and I've noticed some missing methods

/AppKit/CoreAnimation/CAAnimation.j: Line 131 `[anObject addAnimation:self forKey:aKey];` cannot resolve reference to `[anObject addAnimation:forKey:]`

/AppKit/CoreAnimation/CALayer.j: Line 525: `return [_delegate displayInLayer:self];` closest match is `[_delegate displayLayer:]` as defined in the comment on line 63 and `[_delegate respondsToSelector:@selector(displayLayer:)];` on line 963.

/AppKit/CPTextView/CPTextContainer.j: Line 172: `[self _removeAllLines];` not defined in CPTextContainer, or anywhere else I could find.

/AppKit/CPTextView/_CPRTFParser: Lines 122 & 130: call are made to `[CPNumber numberWithInteger:]` but defined as `[CPNumber numberWithInt:]`

/AppKit/CPTextView/_CPRTFProducer: Line 192: cannot resolve `[val sizeValue]` where `val = [docDict objectForKey:PAPERSIZE]`

/AppKit/CoreGraphics/CGContentVML.j: 
	Line 295 `[aGradient.vml_gradient stops]` where is `[* stops]` method located?
	Line 306 `[[stops[i] color] colorForSlideBase:nil]` where is `[* colorForSlideBase:]` method located?

/AppKit/Themes/Aristo/ThemeDescriptors.j: Line 2155, semi-colon after method declaration in an implementation. Should this be allowed in syntax checking?

/AppKit/CPLevelIndicator.j: Line 295 & 304: Semi-colon `- (void)setWarningValue:(double)warningValue;` & `- (void)setCriticalValue:(double)criticalValue;` both have method bodies after the semi-colon. Should this be allowed when checking syntax?

/AppKit/CPSavePanel.j: Line 77: `[[self class] proposedFileURLWithDocumentName:documentName]` cannot resolve` [* proposedFileURLWithDocumentName:]`

/AppKit/CPTabView.j: Line 706: `[_source _setPlaceholderView:aValue]` cannot find `[* _setPlaceholderView:]`

/Foundation/CPPredicate/_CPFunctionExpression.j: Line 223: `else ([object isKindOfClass:[CPArray class]])` is possibly missing `if` as in `else if ([object isKindOfClass:[CPArray class]])`

/Foundation/CPPredicate/_CPSubqueryExpression.j: Line 73: `- (BOOL)isEqual:(id)object;` method has a semi-colon before method body

/Foundation/CPCoder.j: Line 85…: `[self encodeNumber:aPoint.x]` closest match I could find is `[CPKeyedArchiver encodeNumber:forKey:]` not sure where to find simply `[* encodeNumber:]`

/Foundation/CPKeyedArchiver.j: 
	line 194: `_CPKeyedArchiverDidFinishEncodingSelector` should possibly be `_CPKeyedArchiverWillFinishEncodingSelector` as the next line calls `[_delegate archiverWillFinish:self]`
	line 195: `[_delegate archiverWillFinish:self]` is called, but when checking selectors it validates `_delegate against @selector(archiver:willFinishEncoding:)` on line 305 with `[_delegate respondsToSelector:@selector(archiver:willFinishEncoding:)]`
	Line 224: `[_delegate archiverDidFinish:self]` is called, but when checking selectors, it validates _delegate against `@selector(archiver:didFinishEncoding:)` on line 302 with `[_delegate respondsToSelector:@selector(archiver:didFinishEncoding:)]`

/Foundations/CPKeyValueObserving: Line 212: `[[self mutableArrayValueForKeyPath:aKeyPath] replaceObjectAtIndexes:indexes withObjects:newValue]` cannot find method with selector `[* replaceObjectAtIndexes:withObjects:]`

/Foundations/CPNumber.j: `[aCoder decodeNumber]` called, but cannot find method `[* decodeNumber]`

**Comment by daboe01** [comment]
@bedalton can you please elaborate on the context? do you get the errors when building cappuccino? or do they happen at runtime in the browser?

**Comment by bedalton** [comment]
I have not had any errors, because I have never really programmed much in Objective-J. I wanted to use an IDE to code Objective-J with, so I decided to write a plugin for Intellij Idea. When viewing the code with the plugin I'm writing, it found these potential problems. I'm not sure if they would cause problems, but for the plugin I wasn't sure if these missing methods are resolved somewhere else, which I would need to know for better code analysis and intellisense. 

Some things seem more problematic, like in CPKeyedArchiver, where it checks for a method with one selector, then calls a different, but similar method that it had not checked for, ie checks for `@selector(archiver:didFinishEncoding:)` then calls `[_delegate archiverDidFinish:self]`.

The other one I was also concerned with was that I'm also not sure if the `else` statement in  `else ([object isKindOfClass:[CPArray class]])` should be `else if`  or if this is valid in Objective-J.

I'm not an experienced programmer in any language, but especially not Objective-J or Objective-C, and I'm just learning about writing tests in Java, my first programming language. I'm not sure how to test if these are actual problems.

Also, at the moment my plugin chokes on missing semi-colons which can be inferred by Javascript engines, but cannot be by my plugin (I've never written a plugin before). I was wondering if it would be possible to update the code to include all "missing" (as my plugin sees) semi-colons and issue a pull request. I'm not actually sure how pull requests work, so I'm not sure if updating a bunch of files to add semi-colons would mess things up for everyone.

**Comment by daboe01** [comment]
@bedalton i do not think that you found real issues. keep in mind that objective J is based on runtime messaging with late binding (aka duck typing). you can never know at compile time whether any object actually can handle any method call.

**Comment by daboe01** [comment]
@bedalton you are more than welcome to fix style issues (i.e. missing semicolons). please take a look at this document: https://github.com/cappuccino/cappuccino/wiki/Contributing-Code

**Comment by daboe01** [comment]
@bedalton as for /Foundation/CPPredicate/_CPFunctionExpression.j: Line 223: you are correct. please go ahead and make a pull request that corrects this.

**Comment by daboe01** [comment]
@bedalton with _removeAllLines and numberWithInteger: you are correct. i will fix this asap. many thanks!

**Comment by bedalton** [comment]
I have been trying to fix the _CPFunctionExpression code, but after cloning the repository, I cannot get the tests to complete successfully, even on new clones from the master. I'm not too familiar with git or any of this, but when I run the test I get the error:

```addFailure test=[ToolsTest testTools]: objj failed expected:<<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version = "1.0"><array><dict><key>line</key><integer>1</integer><key>sourcePath</key><string>{cappuccino_root_directory}/objjErrorTestFile.j</string><key>message</key><string>
@implementation AppController : CPObject{}@end
                                ^
ERROR line 1 in file:{cappuccino_root_directory}/objjErrorTestFile.j: Can&apos;t find superclass CPObject</string></dict></array></plist>
> but was:<<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version = "1.0"><array><dict><key>line</key><integer>1</integer><key>sourcePath</key><string>{cappuccino_root_directory}/objjErrorTestFile.j</string><key>message</key><string>
@implementation AppController : CPObject{}@end                                ^
ERROR line 1 in file:{cappuccino_root_directory}/objjErrorTestFile.j: Can&apos;t find superclass CPObject</string></dict></array></plist>
>

Trace not implemented

Test suite failed with 0 errors and 1 failures and 1311 successes
Total tests : 1312
```

I can't find objjErrorTestFile.j anywhere on my computer nor in the git repository. Is it something I'm supposed to build prior to running the tests?

**Comment by bedalton** [comment]
After trying to read through the test and the response, it seems like the actual output is missing the `\n` after `CPObject{}@end` making the error caret marker show up on the same line, not the next one. I could be wrong though, but that's what it seemed like was happening.

**Comment by daboe01** [comment]
@bedalton did you install cappuccino properly via bootstrap.sh before running the tests?

**Comment by daboe01** [comment]
@bedalton thank you very much for finding these issues!

**Comment by daboe01** [comment]
@bedalton we cannot properly deal with this ticket because some issues are fixed already and others need discussion. please close this ticket and reopen new tickets, one per issue. thank you!
