### ISSUE TITLE
CALayer delegate method mismatch

### ISSUE THREAD

**Issue by bedalton** [cappuccino/cappuccino#2605]
I brought this up in another issue, but was told to break up the issue, but there is a mismatch between the delegate in CALayer, and the actual method called. In CALayer, the delegate method `@delegate  -(void)displayLayer:(CALayer)layer` is declared in the class comment on at https://github.com/cappuccino/cappuccino/blob/69370aa806930cae27a13b1f495ad84282dd6b07/AppKit/CoreAnimation/CALayer.j#L63 and later, on line 963 https://github.com/cappuccino/cappuccino/blob/69370aa806930cae27a13b1f495ad84282dd6b07/AppKit/CoreAnimation/CALayer.j#L963 with a call to `[_delegate respondsToSelector:@selector(displayLayer:)]`. Though I don't know if it causes any actual problems, the delegate is later called on line 525 https://github.com/cappuccino/cappuccino/blob/69370aa806930cae27a13b1f495ad84282dd6b07/AppKit/CoreAnimation/CALayer.j#L525 with `[_delegate displayInLayer:self]`, calling `displayInLayer` not `displayLayer`. I don't know if this is a problem, but it is one of the cases I found while analyzing the code for valid/invalid method calls.

**Comment by daboe01** [comment]
@cacaodev can you please close?

**Comment by cacaodev** [comment]
Fixed with PR #2610. Thank you @bedalton for reporting this.
