### ISSUE TITLE
Fix mixed content error - CPWebViewTest2

### ISSUE THREAD

**Issue by ArgosOz** [cappuccino/cappuccino#2716]
Currently it can throw the error below:

> Mixed Content: The page at '...' was loaded over HTTPS, but requested an insecure resource 'http://www.cappuccino-project.org/'. This request has been blocked; the content must be served over HTTPS.

https://github.com/cappuccino/cappuccino/blob/0a542f9be9d22e549ae8377574c94c149c536b0c/Tests/Manual/CPWebViewTest2/AppController.j#L50

**Comment by cacaodev** [comment]
Duplicate of #2713
