### ISSUE TITLE
CPButtonTest throws an uncaught error

### ISSUE THREAD

**Issue by ArgosOz** [cappuccino/cappuccino#2717]
https://cappuccino-testbook.5apps.com/?t=CPButtonTest

https://github.com/cappuccino/cappuccino/tree/master/Tests/Manual/CPButtonTest

Activate "CPButton Button Type Test" window.

Clicking the "Toggle" button throws the error below:

> Uncaught Error: - [CPFont loadStatus] unrecognized selector sent to instance 0x00...

**Comment by daboe01** [comment]
the underlying issue is that [toggleButton valueForThemeAttribute:@"image" inState:CPThemeStateHighlighted] returns a CPFont instead of the expected value nil.
+#acknowledged
+Theme

**Comment by daboe01** [comment]
this is not related to the recent work of @didierkorthoudt because we see it in 0.9.10

**Comment by daboe01** [comment]
a closer look reveals that this is most likely a nib2cib-related issue.
-Theme
+Tools

**Comment by daboe01** [comment]
as it turns out, this is a bug in Xcode as you can see in the attached screencap.

**Comment by daboe01** [comment]
<img width="1381" alt="bildschirmfoto 2018-05-26 um 23 39 27" src="https://user-images.githubusercontent.com/146335/40580431-34b0f03c-613e-11e8-8aba-30a070bf4b86.png">

**Comment by daboe01** [comment]
am i missing something here?
if this is really true, we should check whether the alternate image is actually an image before we accept it from the xib.
do you guys agree?
