### ISSUE TITLE
A runtime error prevents displaying images inside a CPTableCellView when the images were linked using the Interface Builder.

### ISSUE THREAD

**Issue by ArgosOz** [cappuccino/cappuccino#2730]
I'm using `cappuccino 0.9.10 (2018-06-15 2ac606)`

A runtime error prevents displaying images inside a CPTableCellView when the images were linked using the Interface Builder.

CPImageView inside a View Based CPTableView's CPTableCellView shouldn't throw an unrecognized selector error but it does... 

Here is the reduction:
https://github.com/ArgosOz/CappuccinoIsCSSBasedIssue

Run the project and you'll get the error below:

`Uncaught Error: - [_CPCibCustomResource isCSSBased] unrecognized selector sent to instance 0x00...`

And then...

* Open the Xcode project...
* Find "Table View Cell" in "FirstColumn" 
* Click "Image View"
* Remove the image named "default-flag-icon" from the image combo box...
![screenshot](https://user-images.githubusercontent.com/3820883/41492184-0aa25ca4-7106-11e8-8792-8110ab0eb522.png)
* Save the project.
* Run the project again...

You won't see the error anymore.

**Comment by didierkorthoudt** [comment]
Hi !

I’ll have a look this weekend as this seems to be related with the extension of CPImage I made for Aristo3 (-isCSSBased)

**Comment by didierkorthoudt** [comment]
OK, found. This is related to the _CPCibCustomResource class not implementing new CPImage CSS theming related methods. My bad (didn't view it). I'll propose a fix ASAP.
