### ISSUE TITLE
Setting the color of text in a CPTableview row

### ISSUE THREAD

**Issue by jasperdeb** [cappuccino/cappuccino#2766]
Until now I have used a version of the master (downloaded and compiled 12th of March), now today I have compiled the latest version.

Before, the way I changed the text color in a cell-based CPTableView row in the following delegate

- (void)tableView:(CPTableView)aTableView willDisplayView:(id)aView forTableColumn:(CPTableColumn)aTableColumn row:(CPInteger)rowIndex
{ 
   [aView setTextColor: [CPColor redColor]];
} 

This used to work, but no longer in the master I have compiled today.

**Comment by didierkorthoudt** [comment]
I’ll have a look ASAP at this as this may be related to a fix I proposed and merged. Without having watched, it may be that the theme takes over direct color setting. Keep you informed.

**Comment by didierkorthoudt** [comment]
@jasperdeb Well, indeed this is due to #2744. In fact, #2744 fixes a bad behavior but CPControl -setTextColor was using this bad behavior (without knowing). The fix is easy : in CPControl -setTextColor, instead of using `[self setValue:aColor forThemeAttribute:@"text-color"]`, it must use `[self setValue:aColor forThemeAttribute:@"text-color" inState:[self themeState]]` (just tested and it works).

I'll propose a fix but I have to check for every setValue that doesn't specify the state.
This is also true for reading values...

Sorry for this, I must admit I didn't try to directly setTextColor on a CPTextField. My bad.

**Comment by jasperdeb** [comment]
@didierkorthoudt : Thank you for the follow up!
As I mentioned in #2708, for a textField setting the vertical alignment also doen not work anymore. 

[textFieldTest setVerticalAlignment:CPTopVerticalTextAlignment];

**Comment by didierkorthoudt** [comment]
@jasperdeb Yes, this is related.

**Comment by mrcarlberg** [comment]
@jasperdeb Can you please check if #2767 will help? We want to included this into version 1.0 and need your feedback her.

**Comment by jasperdeb** [comment]
I Will check thuis weekend

**Comment by mrcarlberg** [comment]
@jasperdeb Do you have time to check this now as I want to include this in version 1.0? We need to get a release candidate out as fast as possible.

**Comment by jasperdeb** [comment]
Ok, I'll try this evening. Software testing is not really compatible with my daytime job :)

**Comment by jasperdeb** [comment]
I have tested the PR.

- The setTextColor works again as expected
- Nevertheless the code

textFieldTest = [[CPTextField alloc] init];
    [textFieldTest setVerticalAlignment:CPTopVerticalTextAlignment];
    [tableColumn setDataView:textFieldTest];

does not gives a table row in the TopVerticalAlignment. 
Text is centered towards the middle.

**Comment by didierkorthoudt** [comment]
Ok, I see the problem. You set the alignment before putting in text view in the table. So it’s the normal state that gets the value and it’s the table data vie state that is used in the table. Let me search on this one this evening.

**Comment by didierkorthoudt** [comment]
@jasperdeb OK, could you please try with the new fix proposed in #2767 ?
