### ISSUE TITLE
Image of an actionPopupButton in CPButtonBar does not appear 

### ISSUE THREAD

**Issue by jasperdeb** [cappuccino/cappuccino#2770]
When I compile the latest master, the image of the actionPopupButton in a CPButtonBar does not appear anymore.

![image](https://user-images.githubusercontent.com/20356278/44807161-1b52fd80-abc9-11e8-987e-8286c6fa69c4.png)

**Comment by mrcarlberg** [comment]
@jasperdeb Can you help us here with more information how to reproduce this problem. The best should be a small example project that we can debug.

@didierkorthoudt Can you look at this one. Can it be some of your changes?

**Comment by didierkorthoudt** [comment]
@mrcarlberg I’ll have a look. But the + button does appear correctly. Strange.

**Comment by mrcarlberg** [comment]
Yes, that is why I think we need some more information from @jasperdeb how this is done

**Comment by daboe01** [comment]
@didierkorthoudt take a look at 6077d3f4c35f275ae3d65f9db490a8b38ea0f4d4

**Comment by didierkorthoudt** [comment]
This seems related to the same origin than your other problem as the action button takes a special theme state to indicate it is a pull down (vs a pop up). Digging into it.

**Comment by daboe01** [comment]
i bisected it down to 6077d3f

**Comment by didierkorthoudt** [comment]
@jasperdeb Could you please test #2771 ?
