### ISSUE TITLE
capp gen -t NibApplication Doesn't Create Xcode Project File

### ISSUE THREAD

**Issue by aksuska** [cappuccino/cappuccino#2790]
Latest master

**Comment by mrcarlberg** [comment]
Are you sure it has ever done this? Can it be that XcodeCapp creates the project file for a project?

**Comment by aksuska** [comment]
I'm not, actually, since my workflow uses them pretty tightly, but opening the new "project" in XcodeCapp does in fact create an Xcode project file, so I will close this issue.
